[template]
files = [
    ".gitattributes",
    ".gitignore",
    "CODE_OF_CONDUCT.md",
    "SECURITY.md",
    ".github/workflows/pr_reminder.yml",
    ".github/workflows/cleanup.yml",
    "Makefile",
]
