[template]
files = [
    ".gitattributes",
    ".gitignore",
    "CODE_OF_CONDUCT.md",
    "SECURITY.md",
]
# Other files we may decide to add...
maybe = [
    ".github/workflows/deploy.yml",
    "Makefile",
]
